apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp2-immediate-new
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
parameters:
  type: gp2
  zones: us-east-1b,us-east-1d