# gp2-csi-sc.yaml
# Create a StorageClass using the AWS EBS CSI driver with Immediate binding mode
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp2-immediate
provisioner: ebs.csi.aws.com
volumeBindingMode: Immediate
reclaimPolicy: Delete
parameters:
  type: gp2
  fsType: ext4
