apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana
  namespace: monitoring
spec:
  storageClassName: gp2-immediate-new
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
