prometheusOperator:
  admissionWebhooks:
    patch:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault

prometheus:
  prometheusSpec:
    securityContext:
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault

alertmanager:
  alertmanagerSpec:
    securityContext:
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault

grafana:
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault

nodeExporter:
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault

kubeStateMetrics:
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
